apiVersion: v1
kind: Service
metadata:
  name: adminer
  labels:
    type: development
    tier: web
    app: adminer
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    env: development
    tier: web
    app: adminer
  type: LoadBalancer
