apiVersion: v1
kind: Service
metadata:
  name: adminer
  labels:
    type: development
    tier: web
    app: adminer
spec:
  ports:
    - port: 8080
      nodePort: 30808  # 30000-32767
  selector:
    env: development
    tier: web
    app: adminer
  type: NodePort
