apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: adminer
        env: development
        tier: web
    spec:
      containers:
        - image: sqrt3/adminer
          name: adminer
          ports:
            - containerPort: 8080
      restartPolicy: Always
