apiVersion: apps/v1
kind: Deployment
metadata:
  name: maildev
  labels:
    app: maildev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maildev
  template:
    metadata:
      labels:
        app: maildev
    spec:
      containers:
        - image: djfarrelly/maildev
          name: maildev
          ports:
            - containerPort: 80
            - containerPort: 25
