apiVersion: v1
kind: Service
metadata:
  name: maildev
spec:
  ports:
    - name: "http"
      port: 8025
      targetPort: 80
    - name: "smtp"
      port: 1025
      targetPort: 25
  selector:
    app: maildev
  type: LoadBalancer
