apiVersion: v1
kind: Service
metadata:
  name: mailcatcher
  labels:
    type: development
    tier: web
spec:
  ports:
    - name: "http"
      port: 8025
      targetPort: 8080
    - name: "smtp"
      port: 1025
      targetPort: 1025
  selector:
    env: development
    tier: web
    app: mailcatcher
  type: LoadBalancer
