apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mailcatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailcatcher
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mailcatcher
        env: development
        tier: web
    spec:
      containers:
        - image: sqrt3/mailcatcher
          name: mailcatcher
          ports:
            - containerPort: 1080
            - containerPort: 1025
      restartPolicy: Always
