apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailcatcher
  labels:
    app: mailcatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailcatcher
  template:
    metadata:
      labels:
        app: mailcatcher
    spec:
      containers:
        - image: sqrt3/mailcatcher
          name: mailcatcher
          ports:
            - containerPort: 1080
            - containerPort: 1025
