apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: maildev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maildev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: maildev
        env: development
        tier: web
    spec:
      containers:
        - image: djfarrelly/maildev
          name: maildev
          ports:
            - containerPort: 80
            - containerPort: 25
      restartPolicy: Always
