apiVersion: v1
kind: Service
metadata:
  name: memcache
  labels:
    type: development
    tier: db
spec:
  ports:
    - port: 11211
      targetPort: 11211
  selector:
    env: development
    tier: db
    app: memcache
  type: LoadBalancer
