apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-5-6
  labels:
    env: development
spec:
  replicas: 1
  selector:
    matchLabels:
      env: development
      tier: db
      app: mysql-5-6
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        env: development
        tier: db
        app: mysql-5-6
    spec:
      containers:
        - image: mysql:5.6
          name: mysql-5-6
          args:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
      restartPolicy: Always
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: local-pvc-mysql-5-6
