apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-5-6-pv
spec:
  storageClassName: mysql-5-6-data
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: $HOME/opt/var/lib/mysql_5.6

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-5-6-pvc
spec:
  storageClassName: mysql-5-6-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
