apiVersion: v1
kind: Service
metadata:
  name: mysql-5-7
  labels:
    env: development
    tier: db
spec:
  ports:
    - port: 3306
      nodePort: 32307  # 30000-32767
  selector:
    env: development
    tier: db
    app: mysql-5-7
  type: NodePort
