apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-mysql-5-7
  labels:
    type: local
spec:
  storageClassName: mysql-5-7-data
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: $HOME/opt/var/lib/mysql_5.7

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-mysql-5-7
  labels:
    env: development
    tier: storage
spec:
  storageClassName: mysql-5-7-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
