apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-5-7-pv
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: $HOME/.local/data/mysql_5.7

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-5-7-pvc
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
