apiVersion: v1
kind: Service
metadata:
  name: mysql-5-7
  labels:
    env: development
    tier: db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    env: development
    tier: db
    app: mysql-5-7
  type: LoadBalancer
