apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    type: development
    tier: db
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    env: development
    tier: db
    app: redis
  type: LoadBalancer
