apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    env: development
spec:
  replicas: 1
  selector:
    matchLabels:
      env: development
      tier: db
      app: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        env: development
        tier: db
        app: redis
    spec:
      containers:
        - image: redis:4-alpine
          name: redis
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: redis-data
      restartPolicy: Always
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: local-pvc-redis
