apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    type: development
    tier: db
spec:
  ports:
    - port: 6379
      nodePort: 32379  # 30000-32767
  selector:
    env: development
    tier: db
  type: NodePort
