apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-registry
  labels:
    type: local
spec:
  storageClassName: registry-data
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: $HOME/opt/var/lib/registry

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-registry
  labels:
    env: development
    tier: storage
spec:
  storageClassName: registry-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
