apiVersion: v1
kind: PersistentVolume
metadata:
  name: spigot-pv
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 3G
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: $HOME/.local/data/minecraft

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spigot-pvc
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3G
