image:
  tag: "5.7"

auth:
  rootPassword: password

primary: 
  configuration: |-
    [mysqld]
    skip-name-resolve
    explicit_defaults_for_timestamp
    max_allowed_packet=16M
    bind-address=0.0.0.0
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    [client]
    default-character-set=utf8mb4
  persistence:
    enabled: true
    existingClaim: mysql-5-7-pvc
  service:
    type: LoadBalancer

metrics:
  enabled: false
