image:
  tag: latest

architecture: standalone
auth:
  enabled: false

commonConfiguration: |-
  save 60 1000

master:
  service:
    annotations: {}
    type: LoadBalancer
    port: 6379
    targetPort: 6379
  persistence:
    existingClaim: redis-pvc

metrics:
  enabled: false
