version: '3.0'
services:
  postgres:
    container_name: registry
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - $HOME/opt/var/lib/registry:/var/lib/registry
    restart: always
    networks:
      - skynet

networks:
  skynet:
    external: true
