version: '3.0'
services:
  postgres:
    container_name: postgres
    image: postgres:9.6.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "root"
    volumes:
      - $HOME/opt/var/lib/postgres:/var/lib/postgresql/data
    networks:
      - skynet

  mysql_5_7:
    container_name: mysql_5.7
    image: mysql:5.7
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    ports:
      - 3307:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - $HOME/opt/var/lib/mysql_5.7:/var/lib/mysql
    networks:
      - skynet

  mysql_5_6:
    container_name: mysql_5.6
    image: mysql:5.6
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - $HOME/opt/var/lib/mysql_5.6:/var/lib/mysql
    networks:
      - skynet

  mysql_8_0:
    container_name: mysql_8.0
    image: mysql:8.0
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    ports:
      - 3380:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - $HOME/opt/var/lib/mysql_8.0:/var/lib/mysql
    networks:
      - skynet

  redis:
    container_name: redis
    image: redis:4-alpine
    ports:
      - 6379:6379
    volumes:
      - $HOME/opt/var/lib/redis:/data
    networks:
      - skynet

  mongo:
    container_name: mongo
    image: mongo:3.4
    ports:
      - 27017:27017
    volumes:
      - $HOME/opt/var/lib/mongo:/data/db
    networks:
      - skynet

networks:
  skynet:
    external: true
